export const avatarConstants = {
    UPDATE_REQUEST: 'AVATARS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'AVATARS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'AVATARS_UPDATE_FAILURE',

    GETOTHER_REQUEST: 'AVATARS_GETOTHER_REQUEST',
    GETOTHER_SUCCESS: 'AVATARS_GETOTHER_SUCCESS',
    GETOTHER_FAILURE: 'AVATARS_GETOTHER_FAILURE',

    GETALL_REQUEST: 'AVATARS_GETALL_REQUEST',
    GETALL_SUCCESS: 'AVATARS_GETALL_SUCCESS',
    GETALL_FAILURE: 'AVATARS_GETALL_FAILURE',
};
