export const channelConstants = {
	CREATE_CHANNEL_REQUEST: 'CREATE_CHANNNEL_REQUEST',
	CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNNEL_SUCCESS',
	CREATE_CHANNEL_FAILURE: 'CREATE_CHANNNEL_FAILURE',

	CREATE_MSG_FOR_REQUEST: 'CREATE_MSG_FOR_REQUEST',
	CREATE_MSG_FOR_SUCCESS: 'CREATE_MSG_FOR_SUCCESS',
	CREATE_MSG_FOR_FAILURE: 'CREATE_MSG_FOR_FAILURE',

	OPEN_CONV_REQUEST: 'OPEN_CONV_REQUEST',
	OPEN_CONV_SUCCESS: 'OPEN_CONV_SUCCESS',
	OPEN_CONV_FAILURE: 'OPEN_CONV_FAILURE',

	GET_MY_CHAN_REQUEST: 'GET_MY_CHAN_REQUEST',
	GET_MY_CHAN_SUCCESS: 'GET_MY_CHAN_SUCCESS',
	GET_MY_CHAN_FAILURE: 'GET_MY_CHAN_FAILURE',

	GET_CHAN_REQUEST: 'GET_CHAN_REQUEST',
	GET_CHAN_SUCCESS: 'GET_CHAN_SUCCESS',
	GET_CHAN_FAILURE: 'GET_CHAN_FAILURE',

	JOIN_CHAN_REQUEST: 'JOIN_CHAN_REQUEST',
	JOIN_CHAN_SUCCESS: 'JOIN_CHAN_SUCCESS',
	JOIN_CHAN_FAILURE: 'JOIN_CHAN_FAILURE',

	RM_CHAN_REQUEST: 'RM_CHAN_REQUEST',
	RM_CHAN_SUCCESS: 'RM_CHAN_SUCCESS',
	RM_CHAN_FAILURE: 'RM_CHAN_FAILURE',

	EDIT_PWD_CHAN_REQUEST: 'EDIT_PWD_CHAN_REQUEST',
	EDIT_PWD_CHAN_SUCCESS: 'EDIT_PWD_CHAN_SUCCESS',
	EDIT_PWD_CHAN_FAILURE: 'EDIT_PWD_CHAN_FAILURE'
};
