export const channelConstants = {
	CREATE_CHANNEL_REQUEST: 'CREATE_CHANNNEL_REQUEST',
	CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNNEL_SUCCESS',
	CREATE_CHANNEL_FAILURE: 'CREATE_CHANNNEL_FAILURE',

	CREATE_MSG_FOR_REQUEST: 'CREATE_MSG_FOR_REQUEST',
	CREATE_MSG_FOR_SUCCESS: 'CREATE_MSG_FOR_SUCCESS',
	CREATE_MSG_FOR_FAILURE: 'CREATE_MSG_FOR_FAILURE',

	OPEN_CONV_REQUEST: 'OPEN_CONV_REQUEST',
	OPEN_CONV_SUCCESS: 'OPEN_CONV_SUCCESS',
	OPEN_CONV_FAILURE: 'OPEN_CONV_FAILURE',
};
