export const friendConstants = {
    ACCEPT_REQUEST: 'FRIENDS_ACCEPT_REQUEST',
    ACCEPT_SUCCESS: 'FRIENDS_ACCEPT_SUCCESS',
    ACCEPT_FAILURE: 'FRIENDS_ACCEPT_FAILURE',

    GETOTHER_REQUEST: 'FRIENDS_GETOTHER_REQUEST',
    GETOTHER_SUCCESS: 'FRIENDS_GETOTHER_SUCCESS',
    GETOTHER_FAILURE: 'FRIENDS_GETOTHER_FAILURE',

    PENDING_REQUEST: 'FRIENDS_PENDING_REQUEST',
    PENDING_SUCCESS: 'FRIENDS_PENDING_SUCCESS',
    PENDING_FAILURE: 'FRIENDS_PENDING_FAILURE',

    GETALL_FRIENDS_REQUEST: 'GETALL_FRIENDS_REQUEST',
    GETALL_FRIENDS_SUCCESS: 'GETALL_FRIENDS_SUCCESS',
    GETALL_FRIENDS_FAILURE: 'GETALL_FRIENDS_FAILURE',
};
