export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    AUTH42_REQUEST: 'USERS_AUTH42_REQUEST',
    AUTH42_SUCCESS: 'USERS_AUTH42_SUCCESS',
    AUTH42_FAILURE: 'USERS_AUTH42_FAILURE',

    TURN2FA_REQUEST: 'USERS_TURN_2FA_REQUEST',
    TURN2FA_SUCCESS: 'USERS_TURN_2FA_SUCCESS',
    TURN2FA_FAILURE: 'USERS_TURN_2FA_FAILURE',

    TURN_OFF2FA_REQUEST: 'USERS_TURN_OFF_2FA_REQUEST',
    TURN_OFF2FA_SUCCESS: 'USERS_TURN_OFF_2FA_SUCCESS',
    TURN_OFF2FA_FAILURE: 'USERS_TURN_OFF_2FA_FAILURE',

    AUTHENTIFICATE2FA_REQUEST: 'USERS_AUTHENTIFICATE_2FA_REQUEST',
    AUTHENTIFICATE2FA_SUCCESS: 'USERS_AUTHENTIFICATE_2FA_SUCCESS',
    AUTHENTIFICATE2FA_FAILURE: 'USERS_AUTHENTIFICATE_2FA_FAILURE',

    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    WHOAMI_REQUEST: 'USERS_WHOAMI_REQUEST',
    WHOAMI_SUCCESS: 'USERS_WHOAMI_SUCCESS',
    WHOAMI_FAILURE: 'USERS_WHOAMI_FAILURE',
    
    LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',

    GETOTHER_REQUEST: 'USERS_GETOTHER_REQUEST',
    GETOTHER_SUCCESS: 'USERS_GETOTHER_SUCCESS',
    GETOTHER_FAILURE: 'USERS_GETOTHER_FAILURE',


    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

		GETLOGIN_REQUEST: 'USERS_GETLOGIN_REQUEST',
		GETLOGIN_SUCCESS: 'USERS_GETLOGIN_SUCCESS',
		GETLOGIN_FAILURE: 'USERS_GETLOGIN_FAILURE',

		NAV_GETLOGIN_REQUEST: 'USERS_GETLOGIN_NAV_REQUEST',
		NAV_GETLOGIN_SUCCESS: 'USERS_GETLOGIN_NAV_SUCCESS',
		NAV_GETLOGIN_FAILURE: 'USERS_GETLOGIN_NAV_FAILURE',
};
